export { default as FacebookIcon } from './facebook-icon';
export { default as GithubIcon } from './github-icon';
export { default as InstagramIcon } from './instagram-icon';
export { default as TwitterIcon } from './twitter-icon';
export { default as YoutubeIcon } from './youtube-icon';
export { default as TiktokIcon } from './tiktok-icon';
export { default as ZaloIcon } from './zalo-icon';
export { default as ThreadsIcon } from './threads-icon';
export { default as XIcon } from './x-icon';
