import { Localization } from "@better-auth-ui/core";

export const authLocalization: DeepPartial<Localization> = {
  auth: {
    account: "Account",
    alreadyHaveAnAccount: "Already have an account?",
    alreadyVerifiedYourEmail: "Already verified your email?",
    confirmPassword: "Confirm password",
    confirmPasswordPlaceholder: "Confirm your password",
    checkYourEmail: "Check your email for a verification link",
    checkYourEmailTitle: "Check your email",
    continueWith: "Continue with {{provider}}",
    email: "Email",
    emailPlaceholder: "m@example.com",
    fieldRequired: "This field is required",
    forgotPassword: "Forgot Password",
    forgotPasswordLink: "Forgot password?",
    hidePassword: "Hide password",
    invalidEmail: "Please enter a valid email address",
    invalidResetPasswordToken: "Invalid reset password token",
    name: "Name",
    namePlaceholder: "Name",
    needToCreateAnAccount: "Need to create an account?",
    newPassword: "New password",
    newPasswordPlaceholder: "New password",
    openEmailProvider: "Open {{provider}}",
    or: "OR",
    optional: " (optional)",
    password: "Password",
    passwordPlaceholder: "Password",
    passwordResetEmailSent: "Password reset email sent",
    passwordResetErrorDescription: "Unable to reset your password. Try again.",
    passwordResetSuccess: "Password reset successfully",
    passwordResetSuccessDescription:
      "Password reset successfully. You can sign in with your new password.",
    passwordsDoNotMatch: "Passwords do not match",
    rememberMe: "Remember me",
    tooLong: "Must be at most {{max}} characters",
    tooShort: "Must be at least {{min}} characters",
    rememberYourPassword: "Remember your password?",
    resend: "Resend",
    resendIn: "Resend in {{seconds}}s",
    resetLinkSentTo: "We sent a password reset link to {{email}}",
    resetPassword: "Reset Password",
    sendResetLink: "Send reset link",
    scanToOpenEmailProvider: "Scan to open {{provider}} on your phone",
    showPassword: "Show password",
    signIn: "Sign In",
    signOut: "Sign Out",
    signUp: "Sign Up",
    verificationEmailSent: "Verification email sent!",
    verifyEmail: "Verify Email",
  },
  settings: {
    account: "Account",
    accountUnlinked: "Account unlinked",
    active: "Active",
    activeSessions: "Active sessions",
    freshSessionTitle: "Confirm it’s you",
    freshSessionDescription:
      "Enter your password again to manage this sensitive setting.",
    freshSessionSubmit: "Confirm and continue",
    freshSessionSignIn: "Sign in again",
    freshSessionSuccess: "Your identity was confirmed.",
    avatar: "Avatar",
    currentSession: "Current session",
    avatarChangedSuccess: "Avatar changed successfully",
    avatarDeletedSuccess: "Avatar deleted successfully",
    changeAvatar: "Change avatar",
    deleteAvatar: "Delete avatar",
    link: "Link",
    linkedAccounts: "Linked accounts",
    linkProvider: "Link your {{provider}} account",
    cancel: "Cancel",
    copyToClipboard: "Copy to clipboard",
    copiedToClipboard: "Copied to clipboard",
    changeEmail: "Change email",
    changeEmailSuccess: "Check your email to confirm the change",
    changePassword: "Change password",
    changePasswordSuccess: "Password changed successfully",
    currentPassword: "Current password",
    currentPasswordPlaceholder: "Enter your current password",
    dangerZone: "Danger zone",
    delete: "Delete",
    optional: "Optional",
    profileUpdatedSuccess: "Profile updated successfully",
    revoke: "Revoke",
    revokeSession: "Revoke session",
    revokeSessionSuccess: "Session revoked successfully",
    saveChanges: "Save changes",
    setPassword: "Set password",
    setPasswordDescription:
      "You don't have a password yet. Request a reset link to set one up.",
    security: "Security",
    settings: "Settings",
    time: "Time",
    unlinkProvider: "Unlink {{provider}}",
    updateEmail: "Update email",
    updatePassword: "Update password",
    uploadAvatar: "Upload avatar",
    userProfile: "User profile",
  },
};

export const authLegalCopy = {
  BY_CONTINUING_YOU_AGREE: "By continuing, you agree to our",
  TERMS_OF_SERVICE: "Terms of Service",
  PRIVACY_POLICY: "Privacy Policy",
};

type DeepPartial<T> = T extends object
  ? { [P in keyof T]?: DeepPartial<T[P]> }
  : T;
