import { Localization } from "@better-auth-ui/core";

export const authLocalization: DeepPartial<Localization> = {
  auth: {
    account: "Tài khoản",
    alreadyHaveAnAccount: "Đã có tài khoản?",
    alreadyVerifiedYourEmail: "Đã xác minh email?",
    confirmPassword: "Xác nhận mật khẩu",
    confirmPasswordPlaceholder: "Xác nhận mật khẩu của bạn",
    checkYourEmail: "Kiểm tra email để lấy liên kết xác minh",
    checkYourEmailTitle: "Kiểm tra email",
    continueWith: "Tiếp tục với {{provider}}",
    email: "Email",
    emailPlaceholder: "m@example.com",
    fieldRequired: "Trường này là bắt buộc",
    forgotPassword: "Quên mật khẩu",
    forgotPasswordLink: "Quên mật khẩu?",
    hidePassword: "Ẩn mật khẩu",
    invalidEmail: "Vui lòng nhập địa chỉ email hợp lệ",
    invalidResetPasswordToken: "Mã đặt lại mật khẩu không hợp lệ",
    name: "Tên",
    namePlaceholder: "Tên",
    needToCreateAnAccount: "Cần tạo tài khoản mới?",
    newPassword: "Mật khẩu mới",
    newPasswordPlaceholder: "Mật khẩu mới",
    openEmailProvider: "Mở {{provider}}",
    or: "HOẶC",
    optional: " (tùy chọn)",
    password: "Mật khẩu",
    passwordPlaceholder: "Mật khẩu",
    passwordResetEmailSent: "Đã gửi email đặt lại mật khẩu",
    passwordResetErrorDescription:
      "Không thể đặt lại mật khẩu. Vui lòng thử lại.",
    passwordResetSuccess: "Đặt lại mật khẩu thành công",
    passwordResetSuccessDescription:
      "Đặt lại mật khẩu thành công. Bạn có thể đăng nhập bằng mật khẩu mới.",
    passwordsDoNotMatch: "Mật khẩu không khớp",
    rememberMe: "Ghi nhớ",
    tooLong: "Phải tối đa {{max}} ký tự",
    tooShort: "Phải tối thiểu {{min}} ký tự",
    rememberYourPassword: "Đã nhớ mật khẩu?",
    resend: "Gửi lại",
    resendIn: "Gửi lại sau {{seconds}}s",
    resetLinkSentTo: "Chúng tôi đã gửi liên kết đặt lại mật khẩu đến {{email}}",
    resetPassword: "Đặt lại mật khẩu",
    sendResetLink: "Gửi liên kết",
    scanToOpenEmailProvider: "Quét để mở {{provider}} trên điện thoại",
    showPassword: "Hiện mật khẩu",
    signIn: "Đăng nhập",
    signOut: "Đăng xuất",
    signUp: "Đăng ký",
    verificationEmailSent: "Đã gửi email xác minh!",
    verifyEmail: "Xác minh email",
  },
  settings: {
    account: "Tài khoản",
    accountUnlinked: "Đã hủy liên kết tài khoản",
    active: "Đang hoạt động",
    activeSessions: "Các phiên đăng nhập",
    freshSessionTitle: "Xác nhận đó là bạn",
    freshSessionDescription:
      "Nhập lại mật khẩu để quản lý thiết lập nhạy cảm này.",
    freshSessionSubmit: "Xác nhận và tiếp tục",
    freshSessionSignIn: "Đăng nhập lại",
    freshSessionSuccess: "Danh tính của bạn đã được xác nhận.",
    avatar: "Ảnh đại diện",
    currentSession: "Phiên hiện tại",
    avatarChangedSuccess: "Đổi ảnh đại diện thành công",
    avatarDeletedSuccess: "Xóa ảnh đại diện thành công",
    changeAvatar: "Đổi ảnh đại diện",
    deleteAvatar: "Xóa ảnh đại diện",
    link: "Liên kết",
    linkedAccounts: "Tài khoản đã liên kết",
    linkProvider: "Liên kết tài khoản {{provider}}",
    cancel: "Hủy",
    copyToClipboard: "Sao chép",
    copiedToClipboard: "Đã sao chép",
    changeEmail: "Đổi email",
    changeEmailSuccess: "Kiểm tra email để xác nhận thay đổi",
    changePassword: "Đổi mật khẩu",
    changePasswordSuccess: "Đổi mật khẩu thành công",
    currentPassword: "Mật khẩu hiện tại",
    currentPasswordPlaceholder: "Nhập mật khẩu hiện tại",
    dangerZone: "Khu vực nguy hiểm",
    delete: "Xóa",
    optional: "Tùy chọn",
    profileUpdatedSuccess: "Cập nhật hồ sơ thành công",
    revoke: "Thu hồi",
    revokeSession: "Thu hồi phiên",
    revokeSessionSuccess: "Thu hồi phiên thành công",
    saveChanges: "Lưu thay đổi",
    setPassword: "Thiết lập mật khẩu",
    setPasswordDescription:
      "Bạn chưa có mật khẩu. Hãy yêu cầu liên kết đặt lại để thiết lập.",
    security: "Bảo mật",
    settings: "Cài đặt",
    time: "Thời gian",
    unlinkProvider: "Hủy liên kết {{provider}}",
    updateEmail: "Cập nhật email",
    updatePassword: "Cập nhật mật khẩu",
    uploadAvatar: "Tải lên ảnh đại diện",
    userProfile: "Hồ sơ người dùng",
  },
};

export const authLegalCopy = {
  BY_CONTINUING_YOU_AGREE: "Bằng việc tiếp tục, bạn đồng ý với",
  TERMS_OF_SERVICE: "Điều khoản dịch vụ",
  PRIVACY_POLICY: "Chính sách bảo mật",
};

type DeepPartial<T> = T extends object
  ? { [P in keyof T]?: DeepPartial<T[P]> }
  : T;
